### ISSUE TITLE
next button useless in some exercise types

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#16]
since on a correct selection, the exercise is automatically changed

<img width="670" alt="screenshot 2017-05-02 20 26 41" src="https://cloud.githubusercontent.com/assets/464519/25633721/69bba162-2f78-11e7-8736-660813936db4.png">

**Comment by mircealungu** [comment]
actually, there is one good use of the next button.
once the user has selected the right word, display
the translation of the word. something like this.

<img width="688" alt="screenshot 2017-05-02 20 30 11" src="https://cloud.githubusercontent.com/assets/464519/25633748/7d626ff2-2f78-11e7-889f-96ff23f7092d.png">

**Comment by mircealungu** [comment]
also, this would be the moment to replace the question mark with a Feedback button. since the question does not make any more sense once the question has been asked.
we could even remove the choice buttons. they're not needed anymore either.

<img width="648" alt="screenshot 2017-05-02 20 43 29" src="https://cloud.githubusercontent.com/assets/464519/25633770/8f22a13a-2f78-11e7-85fe-66e7d72b796a.png">

**Comment by martinavagyan** [comment]
maybe we can do something similar to facebook, when the user hovers the feedback options appear:
![image](https://cloud.githubusercontent.com/assets/7386708/25633908/06708f2c-2f79-11e7-9bc8-70a5468d05ec.png)

**Comment by mircealungu** [comment]
what i was thinking, is that, for a prototype, it would be good to simply popup a dialog in which to ask the user: What do you want to tell us about this exercise? Until we have sufficient feedback, we do a Wizard-of-oz approach, where we manually address the issues that appear. 

Then when we see an issue appearing frequently, we create a predefined option for it. 

What do you think?

**Comment by martinavagyan** [comment]
don't you think pop up is too intrusive for each exercise :) ? maybe when the exercise set is completed when we present the success pop up there they can have the feedback. 
Or is this just for test users, to see their initial impression?

**Comment by mircealungu** [comment]
noooo. not for each exercise. 
only if the user wants to provide feedback for a given exercise, then we should allow them to type the feedback as opposed to providing them with predefined choices. that's all. makes sense?

**Comment by martinavagyan** [comment]
Now it does! I was a bit confused on the use case :)

**Comment by martinavagyan** [comment]
#52
