### ISSUE TITLE
strange behavior in exercises

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#18]
i am logged in with user x@ who has no bookmarked words.
the session belongs to the user x. 

however, i get exercises from the user nl@ 

i am puzzled.

<img width="1244" alt="screenshot 2017-05-03 00 26 12" src="https://cloud.githubusercontent.com/assets/464519/25642019/77789ed0-2f97-11e7-8e81-9c545b249b50.png">

**Comment by martinavagyan** [comment]
User nl@ is set as default session for testing, in case there is no cookie set for sessionID. 
So in this case, it could not find a sessionID in the cookies that's why you got the default session number. Here is that line: 
https://github.com/mircealungu/practice-as-a-service/blob/master/app.py#L30

**Comment by martinavagyan** [comment]
There should also be a condition to redirect to zeeguu login instead of default: 
` return flask.redirect(https://www.zeeguu.unibe.ch/login)`

**Comment by mircealungu** [comment]
ok. i thought there might be something like this.
indeed. redirecting is the right thing to do in such a case.
