### ISSUE TITLE
Clear selection

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#2]
@martinavagyan @VladTurbureanu: the selection is lingering on the last selected button, even when all the contents of all the buttons have changed. I guess a simple clear selection at the beginning of a new exercise will fix this.

<img width="762" alt="screenshot 2017-02-13 10 28 00" src="https://cloud.githubusercontent.com/assets/464519/22877785/4c551bb4-f1d7-11e6-976c-cf81c0a3b746.png">

**Comment by martinavagyan** [comment]
Fixed
