### ISSUE TITLE
the distraction shield notice appears on the homepage of the exercises

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#38]
do you know why? 

how to replicate: 
- be logged in on zeeguu.unibe.ch
- open https://www.zeeguu.unibe.ch/practice/

<img width="1199" alt="screenshot 2017-05-20 23 34 18" src="https://cloud.githubusercontent.com/assets/464519/26279457/0756d564-3db5-11e7-8071-1b081935b075.png">

**Comment by martinavagyan** [comment]
My guess is that browser cache is not updated. With my account I don't get that. Also the distraction shield is only present in generator and in the home screen generator module is not initialized.

![image](https://cloud.githubusercontent.com/assets/7386708/26279645/8b363b5a-3db9-11e7-8020-5f2bff18689c.png)

Can you maybe try disabling the cache and see if the notice appears?
![image](https://cloud.githubusercontent.com/assets/7386708/26279669/1907014e-3dba-11e7-9d32-77aea2109d68.png)

**Comment by mircealungu** [comment]
cleared the cache, and still the same problem. 
true on the other hand, that if i try this in incognito mode, i don't have the same problem.
thus, probably it's the problem of the extension. i'll try to get the latest version of that, maybe that will help.

**Comment by martinavagyan** [comment]
I think The Distraction Shield team is working on this
