### ISSUE TITLE
making every different type of exercise have its own url

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#47]
would be great, since it would allow us to go back to the main menu.
i have tried too many times to go back to the main menu, only for it to fail.

**Comment by martinavagyan** [comment]
@mircealungu If going back to menu is the issue, I can control the back button, thus terminate exercise and go back to home screen when the back button is pressed.
Nevertheless I can make it so that exercise set can be generated by passing json as a post request. What do you think ?

**Comment by mircealungu** [comment]
Ah. Well, the back button would already be nice! 
I guess the exercises having individual addresses would be probably even better!

**Comment by martinavagyan** [comment]
client side routing #84
