### ISSUE TITLE
missing next button image?

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#57]
<img width="834" alt="screenshot 2017-05-31 01 47 14" src="https://cloud.githubusercontent.com/assets/464519/26609736/28b3fd22-45a3-11e7-93d9-d68f3970a84d.png">

**Comment by martinavagyan** [comment]
that is strange, the image is in there https://www.zeeguu.unibe.ch/practice/static/img/next-ex.svg.

**Comment by mircealungu** [comment]
are you using url_for to specify the link to the image?

**Comment by mircealungu** [comment]
in any case, the relative link to the image is `../static/img/next-ex.svg`. There should be no ..

**Comment by martinavagyan** [comment]
found the problem the pull request solves it. #59
