### ISSUE TITLE
Accept session as argument

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#6]
I was looking today into integrating the exercises in the Zeeguu homepage. The screenshot below shows how the integration looks at the moment with an iframe. 

Now we must make sure that the exercises accept a session as a GET or POST argument. 

<img width="1435" alt="screenshot 2017-03-12 20 19 27" src="https://cloud.githubusercontent.com/assets/464519/23835105/aa7326a6-0761-11e7-9c05-6db1f82311a6.png">

**Comment by martinavagyan** [comment]
I will have a look at how Zeeguu api, and try to implement it during the weekend :)
