### ISSUE TITLE
maybe remove these files from version control?

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#60]
error: Your local changes to the following files would be overwritten by merge:
	src/zeeguu_exercises/static/js/dist/mainEntry.entry.js
	src/zeeguu_exercises/static/js/dist/mainEntry.entry.js.map
	src/zeeguu_exercises/static/js/dist/setCookieEntry.entry.js
	src/zeeguu_exercises/static/js/dist/setCookieEntry.entry.js.map
	src/zeeguu_exercises/static/js/dist/testEntry.entry.js
	src/zeeguu_exercises/static/js/dist/testEntry.entry.js.map

**Comment by martinavagyan** [comment]
I was postponing this :), the pull request #61 fixes it.

**Comment by martinavagyan** [comment]
Now before deploying @mircealungu  you can either run: `webpack` or `npm run build`

**Comment by martinavagyan** [comment]
#61
