### ISSUE TITLE
got the same matching exercise three times in a row :)

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#74]
do you have any idea why this would happen? 

<img width="596" alt="screenshot 2017-06-06 01 22 52" src="https://cloud.githubusercontent.com/assets/464519/26807446/c343bfaa-4a56-11e7-8d83-2998ad6b173c.png">

**Comment by martinavagyan** [comment]
Yes, its because we request 3 bookmarks for exercise 3, and this means that the exercise will run 3 times and will have the same words each time since there are no other bookmarks to play with. 
Since our exercise set will always be mixed we wont have this problem.
