### ISSUE TITLE
would it make sense to have a feedback button available already from the first display

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#76]
for example, here, i simply know that the exercise is wrong... 

another way would be to make sure that we never show a wrong word... intersect with frequency lists 

<img width="1071" alt="screenshot 2017-06-06 11 23 17" src="https://cloud.githubusercontent.com/assets/464519/26822533/a7c58e44-4aaa-11e7-9aa4-97d25df5b0e9.png">

**Comment by martinavagyan** [comment]
In my opinion, making sure that we never show a wrong word is less practical than giving them option to correct it.

**Comment by mircealungu** [comment]
you're right. 
this is another example, where the word would make sense alone, but not in the context. 
the feedback here should have been... this is not a good example...

<img width="1053" alt="screenshot 2017-06-06 11 59 42" src="https://cloud.githubusercontent.com/assets/464519/26823944/bebdc77e-4aaf-11e7-973c-199e9f5d645c.png">

**Comment by martinavagyan** [comment]
#95
