### ISSUE TITLE
can't provide feedback once the exercise session is over

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#82]
i keep clicking on the feedback button and nothing happens. 

<img width="844" alt="screenshot 2017-06-10 22 11 52" src="https://user-images.githubusercontent.com/464519/27005967-e3061ffa-4e29-11e7-84b7-b5ac6b2d3e46.png">

**Comment by martinavagyan** [comment]
there was a small bug in the feedback now its fixed #85
