### ISSUE TITLE
another visual refactoring

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#87]
@martinavagyan ,

i had again the situation in which i wanted to give feedback about a word before
checking... i know that the situation in the figure below is wrong. but i could have
also known upfront that i don't like the text, or any other number of issues. thus
the feedback button could already be present here. 

while thinking where would i put the button i realized that the best place is as in the
figure for me. but i had to move the progress bar to make place for that. 

and i ended up liking the progress bar outside of the card. because if we think about
the card as being an exercise, then the progress bar is outside it. the button that allows
me to provide feedback on the exercise should be inside indeed, but the progress among 
cards is outside. does it make sense to you? 

<img width="901" alt="screenshot 2017-06-12 12 03 04" src="https://user-images.githubusercontent.com/464519/27029208-9d3eb9d4-4f67-11e7-9ccc-f1abd79d2d9b.png">

**Comment by martinavagyan** [comment]
Yes, I like your idea of the redesign, it makes things more logical. A while ago I refactored it this way 
![image](https://user-images.githubusercontent.com/7386708/27029661-9a9fedcc-4f69-11e7-8f4a-87ec67ce3798.png)
We can add the function button there as well: 
![image](https://user-images.githubusercontent.com/7386708/27029874-66eda644-4f6a-11e7-9d25-8b8e8c42dad6.png)
But if you want progress completely detached from the container, we can go with that your version :).

**Comment by mircealungu** [comment]
haha. great minds think alike! nice! 

i think adding a bit of space between the card and the progress won't hurt... also as you like!

**Comment by martinavagyan** [comment]
@mircealungu  would you want the feedback button to be as follows 
![image](https://user-images.githubusercontent.com/7386708/27034087-607e0e5e-4f7c-11e7-84bc-231c8ba8e0a3.png)
Or just present the feedback box impliedly?

**Comment by mircealungu** [comment]
This looks cool here.
The other can remain on the second screen. What do you think?

M.

**Comment by martinavagyan** [comment]
I agree this seems more appropriate on this screen.

**Comment by martinavagyan** [comment]
#95
