### ISSUE TITLE
multi-word selection in exercises?

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#89]
or at least a note saying that you can also type...

<img width="512" alt="screenshot 2017-06-13 14 17 56" src="https://user-images.githubusercontent.com/464519/27081973-3e9f2616-5043-11e7-9517-feb5f491314f.png">

**Comment by martinavagyan** [comment]
how about placeholder for input box?

**Comment by mircealungu** [comment]
i'm not sure what you mean. 

but i think that it's easily done: instead of replacing the current word on click you can simply append the current word. then it's up the the reader to delete words manually?

**Comment by martinavagyan** [comment]
@mircealungu  I meant this
![image](https://user-images.githubusercontent.com/7386708/27136471-b1ad1446-511b-11e7-80de-39342928d8ba.png)
Both are easy solutions, sometimes I miss clicked on words, so I liked to replace them completely. 
In any case,  I will change it as you requested.

**Comment by mircealungu** [comment]
Nice! I like your idea too.

Any one would work, but as soon as possible :)

I just saw that there's more feedback of the same
kind.

Which reminds me -- we should setup an automatic
email system that creates github issues / or forwards
emails to basecamp every time we get feedback in
the system.

M.

[image: Inline image 1]

**Comment by martinavagyan** [comment]
The pull request #90 is made that resolves this issue.

**Comment by martinavagyan** [comment]
#95
