### ISSUE TITLE
hint text should be much lighter

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#92]
see it also here on github... but even lighter than here would be ok! 

<img width="375" alt="screenshot 2017-06-15 12 56 13" src="https://user-images.githubusercontent.com/464519/27178317-1175c70c-51ca-11e7-809e-494539cffa55.png">
<img width="680" alt="screenshot 2017-06-15 12 55 37" src="https://user-images.githubusercontent.com/464519/27178318-11775ca2-51ca-11e7-9ebd-d39f44db2f6d.png">

then again, if the focus would be by default on the text-input field, maybe no hint would be needed...

**Comment by martinavagyan** [comment]
#95
