### ISSUE TITLE
bug in correctness check

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/practice-as-a-service#99]
clicking on the two words appends them to the answer box, but for some reason, with two spaces between themselves. this in turn confuses the correctness check which reports an incorrect answer. 

<img width="914" alt="screen shot 2017-06-21 at 12 31 03" src="https://user-images.githubusercontent.com/464519/27379949-919ebfb2-567d-11e7-8eeb-2df2c0ee502f.png">

**Comment by martinavagyan** [comment]
Interesting, this should not happen since I remove all the spaces from the input. I will try to replicate this.

**Comment by mircealungu** [comment]
i think you remove the spaces on the sides of the string, but not in the middle. or? 
i think the best solution is to go through the string and replace multiple spaces with one... both in the correct answer and the submitted one... which makes me wonder whether there's already a javascript library for that :))
